-- Update pricing_plans with expanded features and AI credits
-- FREE plan
UPDATE pricing_plans SET 
  features = jsonb_build_object(
    'customDomain', false,
    'removeWatermark', false,
    'prioritySupport', false,
    'apiAccess', false,
    'webhooks', false,
    'advancedAnalytics', false,
    'whiteLabel', false,
    'multiCurrency', false,
    'facturX', false,
    'peppol', false,
    'ai_marketing', false,
    'pos', false,
    'webshop_builder', false,
    'visual_editor', false,
    'ai_copywriting', false,
    'ai_images', false,
    'ai_seo', false,
    'ai_coach', false,
    'ai_chatbot', false,
    'ai_ab_testing', false,
    'bol_com', false,
    'bol_vvb_labels', false,
    'amazon', false,
    'ebay', false,
    'social_commerce', false,
    'whatsapp', false,
    'shop_health', false,
    'gamification', false,
    'live_activity', false,
    'loyalty_program', false,
    'recurring_subscriptions', false,
    'multi_warehouse', false,
    'promo_bundles', false,
    'promo_bogo', false,
    'promo_volume', false,
    'promo_giftcards', false
  ),
  ai_credits_monthly = 0,
  included_transactions_monthly = 0,
  transaction_overage_fee = 2.50
WHERE slug = 'free';

-- STARTER plan
UPDATE pricing_plans SET 
  features = jsonb_build_object(
    'customDomain', true,
    'removeWatermark', true,
    'prioritySupport', false,
    'apiAccess', true,
    'webhooks', true,
    'advancedAnalytics', false,
    'whiteLabel', false,
    'multiCurrency', false,
    'facturX', true,
    'peppol', false,
    'ai_marketing', true,
    'pos', false,
    'webshop_builder', false,
    'visual_editor', false,
    'ai_copywriting', true,
    'ai_images', false,
    'ai_seo', false,
    'ai_coach', false,
    'ai_chatbot', false,
    'ai_ab_testing', false,
    'bol_com', false,
    'bol_vvb_labels', false,
    'amazon', false,
    'ebay', false,
    'social_commerce', false,
    'whatsapp', false,
    'shop_health', true,
    'gamification', true,
    'live_activity', false,
    'loyalty_program', false,
    'recurring_subscriptions', false,
    'multi_warehouse', false,
    'promo_bundles', true,
    'promo_bogo', true,
    'promo_volume', true,
    'promo_giftcards', true
  ),
  ai_credits_monthly = 50,
  included_transactions_monthly = 100,
  transaction_overage_fee = 0.50
WHERE slug = 'starter';

-- PRO plan
UPDATE pricing_plans SET 
  features = jsonb_build_object(
    'customDomain', true,
    'removeWatermark', true,
    'prioritySupport', true,
    'apiAccess', true,
    'webhooks', true,
    'advancedAnalytics', true,
    'whiteLabel', false,
    'multiCurrency', true,
    'facturX', true,
    'peppol', true,
    'ai_marketing', true,
    'pos', true,
    'webshop_builder', true,
    'visual_editor', true,
    'ai_copywriting', true,
    'ai_images', true,
    'ai_seo', true,
    'ai_coach', true,
    'ai_chatbot', true,
    'ai_ab_testing', true,
    'bol_com', true,
    'bol_vvb_labels', true,
    'amazon', false,
    'ebay', false,
    'social_commerce', true,
    'whatsapp', true,
    'shop_health', true,
    'gamification', true,
    'live_activity', true,
    'loyalty_program', true,
    'recurring_subscriptions', true,
    'multi_warehouse', true,
    'promo_bundles', true,
    'promo_bogo', true,
    'promo_volume', true,
    'promo_giftcards', true
  ),
  ai_credits_monthly = 500,
  included_transactions_monthly = 1000,
  transaction_overage_fee = 0.25
WHERE slug = 'pro';

-- ENTERPRISE plan - unlimited = -1
UPDATE pricing_plans SET 
  features = jsonb_build_object(
    'customDomain', true,
    'removeWatermark', true,
    'prioritySupport', true,
    'apiAccess', true,
    'webhooks', true,
    'advancedAnalytics', true,
    'whiteLabel', true,
    'multiCurrency', true,
    'facturX', true,
    'peppol', true,
    'ai_marketing', true,
    'pos', true,
    'webshop_builder', true,
    'visual_editor', true,
    'ai_copywriting', true,
    'ai_images', true,
    'ai_seo', true,
    'ai_coach', true,
    'ai_chatbot', true,
    'ai_ab_testing', true,
    'bol_com', true,
    'bol_vvb_labels', true,
    'amazon', true,
    'ebay', true,
    'social_commerce', true,
    'whatsapp', true,
    'shop_health', true,
    'gamification', true,
    'live_activity', true,
    'loyalty_program', true,
    'recurring_subscriptions', true,
    'multi_warehouse', true,
    'promo_bundles', true,
    'promo_bogo', true,
    'promo_volume', true,
    'promo_giftcards', true
  ),
  ai_credits_monthly = -1,
  included_transactions_monthly = -1,
  transaction_overage_fee = 0
WHERE slug = 'enterprise';